### ISSUE TITLE
mail filter backup

### ISSUE THREAD

**Issue by antonzhelyazkov** [Zmbackup/zmbackup#36]
Hi,

You could add users mail filter backup. I wrote simple script to do it

cat /backups/zmigrate/filters-export.sh
#!/bin/bash
set -x
clear
echo “Retrieve zimbra user name…”
USERS=`cat /backups/zmigrate/emails.txt`;
for ACCOUNT in $USERS; do
NAME=`echo $ACCOUNT`;
filter=`su – zimbra -c “zmprov ga $NAME zimbraMailSieveScript” > /tmp/$NAME`
sed -i -e “1d” /tmp/$NAME
sed ‘s/zimbraMailSieveScript: //g’ /tmp/$NAME > /backups/zmigrate/filters/$NAME;
rm /tmp/$NAME
echo “Export filter for $NAME…”
done
echo “All filter has been export successfully”

And script for import filters:

#!/bin/bash
set -x
for file in /backups/zmigrate/filters/*
do
StrFilter=`cat “$file”`
Acc=$file
su – zimbra -c “zmprov ma $(echo $file | grep -E -o “\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b”) zimbraMailSieveScript ‘$StrFilter'”
echo “Process filter $Acc”
done
echo “All filter has been import successfully”

**Comment by lucascbeyeler** [comment]
Good morning @antonzhelyazkov ,

I'm going to implement this in the next release of Zmbackup (1.2). About your code, can you provide the same solution, but with the ldapsearch command? Zmprov is a little slow to execute and I think it will affect the entire backup process...

Regards,

Lucas Costa Beyeler
